# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: []
  pull_request:
    branches: ["!master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Checks:
    runs-on: self-hosted
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: setup environment
        run:
          sudo ./scripts/setup-all.sh
      - name: Codestyle
        run:
          scripts/codestyle.sh
      - name: AddressSanitizer
        run:
          scripts/asan.sh
      - name: ThreadSanitizer
        run:
          scripts/tsan.sh
      - name: Coverage
        run:
          scripts/coverage.sh
